- Makefile
- manifests/dynamic-networks-controller.yaml
This PR points to a manually released image.
Eventually, the right thing to do is use CI best practices to automatically release these images.
> deployment: default to proper published img

- cmd/dynamic-networks-controller/networks-controller.go
- manifests/dynamic-networks-controller.yaml
- templates/dynamic-networks-controller.yaml.j2
Depends-on: #16 
This PR ensures the hostname of the controller pods is the name of the nodes where they are scheduled.
This enables the controller to listen exclusively to events on the node where it is deployed, and thus request delegates from multus for pods scheduled on the node it manages.
> Fix each ds instance listens to events on its node

- .github/workflows/check.yaml
- .github/workflows/e2e-container.yaml
- .gitignore
- e2e/test-provisioning-examples.sh
- hack/e2e-kind-cluster-setup.sh
This PR adds a kind based cluster to check the e2e functionality of the repo.
It simply runs the e2e scripts of the multus project, which for now, is more than enough for us.
Follow-up PRs will add a golang based e2e test suite to check the functionality of the project.
Depends-on: #20 
Fixes: #7
> Add kind e2e

- .github/workflows/image-push.yaml
Previously we were attempting to push images on changes to the `master` branch ... which didn't exist in this project.
> ci, img push: push images when main branch is updated

- Makefile
- hack/e2e-kind-cluster-setup.sh
- hack/generate_manifests.sh
- manifests/dynamic-networks-controller.yaml
- templates/dynamic-networks-controller.yaml.j2
Now that we automatically build & push the latest version of the controller to github's registry, we can update the project's manifests to feature said registry.
Signed-off-by: Miguel Duarte Barroso <mdbarroso@redhat.com>
> deploy: use github container registry

- Makefile
- hack/generate_manifests.sh
- templates/dynamic-networks-controller.yaml.j2
As an administrator, I don't want to instal external components under Kubernetes' kube-system.
This patch allows me to easily parametrize the target namespace.
> Allow templating of namespace in manifests

- e2e/client/types.go
We were mistakenly using an hard-coded value. Luckily, it was the correct one - but this would explode the moment someone added an e2e test that attempted to hot plug a network to a pod on a namespace other than `ns1`.
Fixes #
> e2e: use namespace param when hotplugging

- go.mod
- go.sum
- pkg/controller/pod.go
- vendor/gopkg.in/k8snetworkplumbingwg/multus-cni.v3/pkg/server/api/api.go
- vendor/gopkg.in/k8snetworkplumbingwg/multus-cni.v3/pkg/server/api/types.go
- vendor/modules.txt
This PR updates the multus dependency to a version that allows specifying the runtime config.
With this, it is now possible for a particular pod to specify particular interface attributes, like MAC / IP addresses.
Fixes #
> build, multus: go get multus-cni w/ runtime config

- e2e/client/types.go
- e2e/e2e_test.go
This PR adds tests asserting runtime configuration (pod / MAC addresses) can be requested for the delegate being added.
It also adds an e2e test proving that removing an interface with runtime configuration is possible.
Fixes #42 
> Send desired IP / MAC address to multus server

- examples/interface-add.yaml
- examples/interface-remove.yaml
- examples/original-setup.yaml
We currently cannot hotplug an interface if it doesn't feature the `name` attribute in the plugin configuration.
This happens because we compute the delegate CNI configuration directly from that JSON config.
Furthermore, the examples are updated to provide the following:
- hotplug w/ IP configuration
- hotplug w/ MAC address configuration
- hotunplug (cannot hot-unplug if the interface name is not shown in the `NetworkSelectionElement`)
Fixes #
Depends-on: #39
> Correct the provided examples

- e2e/client/types.go
- e2e/e2e_test.go
- pkg/controller/pod.go
This PR allows hot-plugging interfaces into a pod without any `network-selection-elements`.
Fixes #43
> Handle old pods without network selection elements

- hack/generate_manifests.sh
- manifests/scc.yaml
- templates/scc.yaml.j2
This PR provides an SCC manifest, without which deployment of the project in an Openshift cluster would fail, since mounting host file system paths requires the following permissions to be granted (for Openshift clusters):
- hostPath volume
- allowHostDirVolumePlugin (if false it overrides the `hostPath` volume entry)
- allowPrivilegedContainer (we need to be privileged, since multus-cni container is privileged. We wouldn't be able to use the socket otherwise).
Fixes #33 
> Add scc template

- e2e/client/types.go
Idiomatic go is pretty and easier to read.
> Refactor a helper function to follow the happy path

- README.md
This PR updates the documentation indicating the project has reached what I consider to be the MVP.
Fixes #
> docs: reach MVP milestone

- .github/workflows/image-push.yaml
This PR adds automation to perform github releases (which point at properly tagged container images).
> CI: release when properly tagged

- .github/workflows/image-push.yaml
Signed-off-by: Miguel Duarte Barroso <mdbarroso@redhat.com>
The correct syntax for the `gh-release` github action is:
```yaml
- name: Release
uses: softprops/action-gh-release@v1
if: startsWith(github.ref, 'refs/tags/')
with:
files: Release.txt
```
Fixes #
> ci, release: was missing with clause

- .github/workflows/image-push.yaml
We cannot template the manifests without the `j2` depedency. This PR install it for the `image-push` action.
> ci, release: templating the manifest requires j2

- .github/workflows/image-push.yaml
Now that we know the release machine does what it is supposed to do, we can stop reacting to this dummy tag.
This reverts commit 3eebfc0d46720a41a68836ba350494b6e86d22fc.
> Revert "ci, release: add dummy tag to test this works"

- README.md
- e2e/e2e_test.go
- pkg/controller/pod.go
This PR enables the pod network's controller to add / remove network interfaces to networks that do **not** feature the `name` attribute in `spec.config`.
Fixes #45 
> controller: allow hot[plug|unplug] for nets without spec.config.name

- .github/workflows/e2e-containerd.yaml
- e2e/e2e_test.go
This PR enables [CNAO](https://github.com/kubevirt/cluster-network-addons-operator) e2e test framework to successfully run the `multus-dynamic-networks-controller` e2e tests.
That is a requirement for the CNAO operator to ship a project.
Fixes #
Once CNAO's test framework bumps their containernetworking plugins version, we can resume using plugins of version 1.0.0 on the tests.
> Fix e2e tests for cnao deployment

- .github/workflows/image-push.yaml
- Makefile
- cmd/dynamic-networks-controller/networks-controller.go
- e2e/client/types.go
- e2e/e2e_test.go
- e2e/status/helpers.go
- go.mod
- hack/e2e-kind-cluster-setup.sh
- manifests/crio-dynamic-networks-controller.yaml
- manifests/dynamic-networks-controller.yaml
- pkg/config/types.go
- pkg/config/types_test.go
- pkg/controller/pod.go
- pkg/controller/pod_test.go
- pkg/cri/containerd/runtime_test.go
- pkg/cri/crio/fake/runtime.go
- pkg/cri/crio/runtime.go
- pkg/cri/crio/runtime_test.go
Formalize the handover to the `k8snetworkplumbingwg` organization.
Fixes #
> Rename repo pkg

- .github/workflows/image-push.yaml
We were only passing the git commit id for tagged images. 
This feature is most useful for the `latest` tagged image.
Fixes 
> ci: pass the commit ID via github actions also for `latest-amd64`

- .github/workflows/image-push.yaml
Seems now we are indeed labeling the image via the build args, but we are failing to get the correct value; this is what I get currently:
```bash
skopeo inspect docker://ghcr.io/k8snetworkplumbingwg/multus-dynamic-networks-controller:latest-amd64 -f '{{ index .Labels "multi.GIT_SHA" }}'
```
This means the value of `github.event.pull_request.head.sha` is an empty string.
This PR uses github env instead to pass the values along to the image builder.
Fixes #
> build, ci: embed the git commit id via GITHUB_ENV

- pkg/annotations/dynamic-network-status.go
- pkg/annotations/dynamic-network-status_test.go
- pkg/controller/pod.go
Until we have a level driven controller, the embedded retry-on-conflict embedded in the library might come in handy.
The controller must be refactored to compare the network selection elements with whatever is on the status annotation, rather than comparing old & new network selection elements.
Finally, this refactor should evaluate if we want to have a separate annotation for dynamic attachments. This should be pitched to the k8snetworkplumberswg.
**Special notes for your reviewer** (optional):
Depends-on: #83
> controller: update status via the net-attach-def-client lib

- README.md
- pkg/annotations/dynamic-network-status.go
- pkg/annotations/dynamic-network-status_test.go
- pkg/annotations/network-selection-elements.go
- pkg/annotations/network-selection-elements_test.go
- pkg/annotations/types.go
- pkg/controller/pod.go
- pkg/controller/pod_test.go
- pkg/multuscni/fake/client.go
Re-write the controller as level driven, instead of edge-triggered.
This makes user interaction more resilient, since the controller will try to materialize the desired state (network-selection-elements) into the current state (network-status).
There is one behavior that needs to be highlighted: the existing interfaces need to always feature the interface name in the desired state (network selection elements); take the following example:
- initially, there is a secondary interface in the pod for which the user did not name explicitly.
- at t=1, the user attempts to hotplug interfaces; these will fail
- at t=2, the user corrects the desired state, manually specifying the name of the interface for the existing attachment
- the controller will …
> Level driven controller

- pkg/controller/pod.go
- pkg/controller/pod_test.go
This PR rejects adding / removing interfaces to/from host networked pods.
The controller unit tests were refactored a bit - creating the k8s client and the dummy controller - in a `JustBeforeEach` block to allow each `When` / `Context` block to define the pod previously. This way, there is a lot less duplicated code.
Fixes #88
> controller: reject adding ifaces to host networked pods

- cmd/dynamic-networks-controller/networks-controller.go
- pkg/controller/pod.go
ensure that we don't miss updated made to pods' networks before the controller get started
Signed-off-by: Abdallah Chatila <abdallah@kaloom.com>
In case updates were made to pods's networks while the controller is not present on a node we currently miss reconciling them
Fixes #
filtering out pods that are of no concern for the controller (e.g. `pod.Spec.HostNetwork == true`) can be ideally be put in a separate function that can be used by both `handlePodUpdate` function on pods updates and `reconcileOnStartup` function included here when doing …
> controller: reconcile pods on startup

- Makefile
- hack/generate_manifests.sh
- manifests/crio-dynamic-networks-controller.yaml
- manifests/dynamic-networks-controller.yaml
- templates/dynamic-networks-controller.yaml.j2
Signed-off-by: Miguel Duarte Barroso <mdbarroso@redhat.com>
This PR adds a liveness probe to the controller; it continuously queries the multus-cni `healthz` endpoint, and restarts the controller pods whenever it fails to contact the multus API.
With this, we ensure the controller always has access to the correct multus socket to contact the multus server API.
Fixes #96 
Multus-cni was added the `healthz` endpoint in https://github.com/k8snetworkplumbingwg/multus-cni/pull/963
> multus: liveness check multus

- .github/dependabot.yaml
The kubernetes dependencies should be updated on demand.
Fixes #
> dependabot: ignore k8s dependency updates

- .github/workflows/check.yaml
- .github/workflows/e2e-containerd.yaml
- go.mod
- images/Dockerfile
- pkg/controller/pod_test.go
Signed-off-by: Miguel Duarte Barroso <mdbarroso@redhat.com>
This PR bumps the golang version to 1.19.
Fixes #
> build, ci, test: bump to golang 1.19

- e2e/e2e_test.go
Sometimes 2 seconds can be not enough on CI to reconcile the attachments
for a pod when a pod does not feature the interface names; also, this timeout
is also used for a `Consistently` clause, where 2 seconds is also too little.
Thus, let's give it some more time.
Fixes #124 
> E2e bump timeouts

- hack/e2e-kind-cluster-setup.sh
We must use the dockerfile for the thick plugin version - we were using the multus setup script default, which is to use the thin version.
Up to now this was not an issue since the thin version featured the `cp` command, which is used on the thick-plugin initcontainer. Now that the thin plugin version daemonset spec was updated (it no longer features the `cp` command), the thick plugin version init container fails to perform its task.
Fixes #134 
> ci, build: use the correct dockerfile image

- e2e/e2e_test.go
This PR addresses failing e2e tests on kubevirtci providers.
It increases the timeouts a little bit, but the most important thing it does is ensure all pods are gone between tests, since the error we were seeing was a statically defined mac address being already used (which means the previous pod using it, is not yet deleted).
Fixes #140
> Fix e2e tests on crio providers

- .github/workflows/check.yaml
- .golangci.yml
- pkg/controller/pod.go
- pkg/controller/pod_test.go
The CNI args has to be set in the delegate request so the cni-args in the network attachment annotation are considered.
Fixes #
> Controller: Set CNI args on the delegate request

- pkg/annotations/dynamic-network-status.go
- pkg/controller/pod.go
- pkg/controller/pod_test.go
The controller is now setting the pod network status annotation only once in the reconcile loop to avoid conflicts when a network attachment is added and another one removed at the same time.
Fixes: #157
> Controller: handle add/remove in the same reconciliation

- .github/workflows/e2e-containerd.yaml
This PR bumps the setup-python version to v4, thus removing the following warning from CI:
```
e2e-tests
The following actions uses node12 which is deprecated and will be forced to run
on node16: actions/setup-python@v2.
```
Link to a failure:
https://github.com/k8snetworkplumbingwg/multus-dynamic-networks-controller/actions/runs/6416838930
Fixes #
> ci: bump setup-python github action version

- e2e/e2e_test.go
This PR reads the HOME variable from the environment, thus allowing the e2e test framework to properly default the path to the kubeconfig.
Fixes #
> e2e: read the value of the HOME env var

- e2e/client/types.go
- e2e/e2e_test.go
Add an e2e test asserting this new desired behavior (add and remove attachments in the same operation).
Fixes #
I'm also adjusting the timeouts in this PR, since locally this consistently passes.
> Add e2e test add remove same op

- .github/workflows/check.yaml
- .github/workflows/e2e-containerd.yaml
- .github/workflows/image-push.yaml
- hack/generate_manifests.sh
j2cli is unmaintained and no longer works with python3.12. It is therefore replaced with an active fork called jinjanator.
Fixes #
> fix: Replace j2cli with jinjanator in GitHub workflows

- Makefile
Make life simpler, add `vendor` target.
We are used to this command on them.
It will ease automation, because it aligns the the same
command on all other network repos.
Fixes #
> makefile: Add vendor target

- pkg/config/types_test.go
- pkg/controller/pod_test.go
- pkg/cri/containerd/runtime_test.go
- pkg/cri/crio/runtime_test.go
client-go recommends to call WaitForCacheSync after calling Start on the SharedInformerFactory.
https://pkg.go.dev/k8s.io/client-go@v0.28.4/informers#SharedInformerFactory
This fixes the flaky unit test for the pod controller.
ginkgo could be updated to its version 2 (github.com/onsi/ginkgo/v2)
**Which issue(s) this PR fixes** *
/
I am not so familiar writing controller only with client-go, usually I use [controller-runtime](https://github.com/kubernetes-sigs/controller-runtime). So I don't really know what is done behind WaitForCacheSync except from what I could read in the documentation.
From what I observed, sometimes, handlePodUpdate is not called with the latest pod changes.
I tried to repeat …
> Fix pod controller flaky unit test

- pkg/annotations/dynamic-network-status.go
- pkg/annotations/network-selection-elements.go
- pkg/controller/pod.go
- pkg/controller/pod_test.go
When adding 2 attachements and the second was failing, the status was not reported in the annotation. Same behavior was happening for deletion.
This is now fixed, and events are also reported in case of failure on adding/deleting annotations.
The order in which attachements are handled is now deterministic to fulfill some special use cases (e.g. macvlan attachement + vlan attachement based on the macvlan) and to improve testing and troubleshooting.
This behavior should be now locked with the pod controller unit tests.
The default network status must be ignored and be kept. A unit test has been added to cover this case.
**Which issue(s) this PR fixes**:
Fixes #194 (3.)
> Fix network status on failing attachement add/delete

- e2e/e2e_test.go
The mac addresses used during the e2e tests are now generated during the tests instead of being hard-coded.
The hard-coded mac address was causing flaky tests probably due to the kernel refusing a new macvlan interface to be created with an already existing mac address.
**Which issue(s) this PR fixes**:
Fixes #194 (1.)
> Fix flaky e2e test due to mac address re-used

- hack/e2e-kind-cluster-setup.sh
The Multus e2e environment is no longer using the local registry. The image is now loaded. The tag has been set to e2e so there is no conflict if the ImagePullPolicy is not set
**Which issue(s) this PR fixes**:
Fixes #
> e2e job: load image in kind

- .github/workflows/check.yaml
- .github/workflows/e2e-containerd.yaml
- .github/workflows/image-push.yaml
softlink removed because file already exists 
https://github.com/k8snetworkplumbingwg/multus-dynamic-networks-controller/actions/runs/11035289947/job/30650904671
was introduced as part of https://github.com/k8snetworkplumbingwg/multus-dynamic-networks-controller/pull/183
Fixes #
> Remove softlink as file exists

- hack/e2e-kind-cluster-setup.sh
Allows to deploy Multus dynamic networks controller on external provider.
Deploys official multus release (doesnt build latest as this repo usually do).
Usage example:
```
export CLUSTER_TYPE=external
export KUBECONFIG=<kubeconfig>
export IMAGE_REGISTRY=quay.io/<your_quay>
export MULTUS_VERSION=v4.1.1
```
If CRIO is used, use `export CRI=crio` (works also for non external clusters).
Note kubevirtci clusters require it.
If You don't want to deploy multus at all use (you must deploy it yourself as the controller depends on it)
`export SKIP_MULTUS_DEPLOYMENT=true` (supported only for external clusters)
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets …
> cluster: Allow deploying controller on external cluster

- pkg/controller/pod.go
- pkg/controller/pod_test.go
This pr delete all attachments added in this `processNextWorkItem` when set NetworkStatus failed in `handleResult`.  Because DEL is Idempotence we can always return to the state before dynamic handle.
Fixes #235
> Handle update network status failed after add and del attachments 

- pkg/config/types_test.go
- pkg/controller/pod_test.go
Using defercleanup instead of `AfterEach` blocks is more idiomatic.
Fixes #
> ginkgo: rely on DeferCleanup

- .github/workflows/image-push.yaml
- images/Dockerfile
These changes enable the building of the Multus Dynamic CNI image for multiple platforms (amd64, arm64, s390x) using github actions.
The upstream image of the Multus Dynamic Networks Controller CNI ([link](https://github.com/k8snetworkplumbingwg/multus-dynamic-networks-controller/pkgs/container/multus-dynamic-networks-controller)) currently supports only the amd64 architecture. These changes extend multi-platform support to include arm64 and s390x architectures, enhancing the compatibility of the Multus Dynamic Networks Controller image across a broader range of systems.
Cross-compilation is performed in the builder image using the TARGETOS and TARGETARCH build arguments, which specify the target OS and architecture. These arguments are …
> Add multiarch image build support using github actions.

- .github/workflows/check.yaml
- go.mod
This PR adds a check to CI in order to prevent vendor misalignment 
Fixes #
> Fix go vendor

- manifests/crio-dynamic-networks-controller.yaml
- manifests/dynamic-networks-controller.yaml
- templates/dynamic-networks-controller.yaml.j2
To comply with best practices, all the containers in all the pods, must set the TerminationMessagePolicy field to FallbackToLogsOnError [0]
[0]
https://github.com/redhat-best-practices-for-k8s/certsuite/blob/main/CATALOG.md#observability-termination-policy
Fixes #
> Set container's TerminationMessagePolicy to FallbackToLogsOnError
